    import React from 'react'
    
    export const RefundPolicy = () => {
      return (
       <main id="MainContent" className="content-for-layout" role="main" tabIndex={-1}>              
  <div className="shopify-policy__container">
    <div className="shopify-policy__title">
      <h1>Refund policy</h1>
    </div>
    <div className="shopify-policy__body">
      <div className="rte">
        <p>----</p>
        <p><strong>RETURNS AND EXCHANGES - NORTH AMERICA</strong></p>
        <p>----</p>
        <p>&nbsp;</p>
        <span>AMIRI NOW OFFERS COMPLIMENTARY DOMESTIC RETURN SHIPPING. TO INITIATE A RETURN OR AN EXCHANGE, PLEASE VISIT&nbsp;</span><a href="https://returns.amiri.com/">RETURNS.AMIRI.COM</a><a href="https://web.global-e.com/returns/portal/oQQX">.</a><span /><br /><br /><span>AMIRI CURRENTLY ALLOWS RETURNS AND EXCHANGES WITHIN 20 DAYS OF THE ORDER DELIVERY DATE. ALL RETURNED ITEMS MUST BE UNWORN, UNDAMAGED, AND UNWASHED WITH ALL ORIGINAL TAGS ATTACHED. THE ORIGINAL INVOICE MUST BE INCLUDED WITH ANY RETURN. FAILURE TO DO SO CAN DELAY THE PROCESSING OF YOUR RETURN.</span><br /><br /><span>EXCHANGES CAN BE MADE FOR A DIFFERENT SIZE OR COLOR OF THE ORIGINAL STYLE ORDERED, DEPENDING ON PRODUCT AVAILABILITY. IF YOU WOULD LIKE TO EXCHANGE YOUR ITEM FOR A DIFFERENT STYLE, PLEASE RETURN YOUR ITEM FOR A REFUND AND PLACE A NEW ORDER FOR THE PREFERRED STYLE. UP TO ONE EXCHANGE SHIPMENT WILL BE PAID BY AMIRI.</span><br /><br /><span>RETURNS ARE PROCESSED WITHIN 3-5 BUSINESS DAYS OF ARRIVING AT OUR FACILITY. THIS PERIOD MAY BE LONGER DURING PEAK PERIODS. DEPENDING ON YOUR PAYMENT PROVIDER, IT CAN TAKE UP TO 5-10 BUSINESS DAYS FOR THE REFUNDED AMOUNT TO APPEAR ON YOUR BANK STATEMENT.</span><br /><br /><span>IF AMIRI DETERMINES THAT ANY PRODUCTS ARE NOT IN ORIGINAL CONDITION, A REFUND OR EXCHANGE WILL NOT BE GRANTED AND THE ITEMS WILL BE RETURNED TO YOU.</span><br /><br /><span>IF YOU HAVE ANY QUESTIONS, PLEASE CONTACT CUSTOMER SERVICE AT SUPPORT@AMIRI.COM.</span>
        <p>----</p>
        <p><strong>RETURNS AND EXCHANGES - INTERNATIONAL</strong></p>
        <p>----</p>
        <p><span>AMIRI NOW OFFERS COMPLIMENTARY INTERNATIONAL RETURNS. TO INITIATE A RETURN FOR AN INTERNATIONAL ORDER, PLEASE VISIT&nbsp;</span><a href="https://web.global-e.com/returns/portal/oQQX">HERE</a><span>.</span><br /><br /><span>INTERNATIONAL ORDERS ARE NOT ELIGIBLE FOR EXCHANGE. IF YOU WOULD LIKE TO EXCHANGE YOUR ITEM FOR A DIFFERENT SIZE, PLEASE RETURN YOUR ITEM FOR A REFUND AND PLACE A NEW ORDER ON AMIRI.COM.</span><br /><br /><span>AMIRI CURRENTLY ALLOWS THE CUSTOMER TO INITIATE A RETURN WITHIN 20 DAYS OF THE ORDER DELIVERY DATE. ALL RETURNED ITEMS MUST BE UNWORN, UNDAMAGED, AND UNWASHED WITH ALL ORIGINAL TAGS ATTACHED. THE ORIGINAL INVOICE MUST BE INCLUDED WITH ANY RETURN. FAILURE TO DO SO CAN DELAY THE PROCESSING OF YOUR RETURN.</span><br /><br /><span>RETURNS ARE PROCESSED WITHIN 3-5 BUSINESS DAYS OF ARRIVING AT OUR FACILITY. A FULL REFUND WILL BE ISSUED UPON THE ARRIVAL AND INSPECTION OF YOUR RETURN. DEPENDING ON YOUR PAYMENT PROVIDER, IT CAN TAKE UP TO 5-10 BUSINESS DAYS FOR THE REFUNDED AMOUNT TO APPEAR ON YOUR BANK STATEMENT. IF AMIRI DETERMINES THAT ANY PRODUCTS ARE NOT IN ORIGINAL CONDITION, A REFUND OR EXCHANGE WILL NOT BE GRANTED AND THE ITEMS WILL BE RETURNED TO YOU.</span><br /><br /><span>IF YOU HAVE ANY QUESTIONS, PLEASE CONTACT CUSTOMER SERVICE AT SUPPORT@AMIRI.COM.</span></p>
      </div>
    </div>
  </div>
</main>

      )
    }
    