name: CICD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -f Dockerfile -t omerkhan7210/zeyr-front:latest .

      - name: Push to Docker Hub
        run: docker push omerkhan7210/zeyr-front:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo docker pull omerkhan7210/zeyr-front:latest
            sudo docker rm -f zeyr-front-container || true
            sudo docker run -d -p 3000:80 --name zeyr-front-container omerkhan7210/zeyr-front
